import { TierId, TIER_IDS, getTierOrdinal } from './ranks';
import { WallTier } from '../types/ProbeBase';

/** Shared scaling constants so walls, shop items and ranks stay in perfect sync. */

// A full rank/cycle advances the upgrade counter by 18 steps (Wall 1-5 -> Ultra 1-5 -> Mega 1-5 -> Power 1-2 -> Final)
export const WALL_CYCLE_STEPS = 18;

// HP multiplier between consecutive wall levels within one cycle (1.5x per level-up)
export const WALL_LEVEL_GROWTH = 1.5;

// HP multiplier on a tier change (Wall -> Ultra -> Mega -> Power -> Final)
export const WALL_TIER_GROWTH = 2.0;

// First Wall of the next rank = 1.5x the Final Wall HP of the previous rank
export const WALL_CYCLE_BOUNDARY_GROWTH = 1.5;

// --- Precomputed per-step tables for O(1) wall computation ---
// Position 0..17 within a wall cycle. Multipliers are EXACT (no intermediate rounding),
// so a wall at any cycle can be computed directly: 200 * CYCLE_STEP_MULTIPLIERS[pos] * CYCLE_TOTAL_GROWTH^cycle.
const STEP_MULT: number[] = [1];
const STEP_DEFENSE: number[] = [2];

let mult = 1;
let defense = 2;
for (let pos = 1; pos < WALL_CYCLE_STEPS; pos++) {
  // Tier changes happen at 5 (Wall5->Ultra1), 10 (Ultra5->Mega1), 15 (Mega5->Power1), 17 (Power2->Final).
  const tierChange = pos === 5 || pos === 10 || pos === 15 || pos === 17;
  mult *= tierChange ? WALL_TIER_GROWTH : WALL_LEVEL_GROWTH;
  defense += tierChange ? 8 : 3;
  STEP_MULT.push(mult);
  STEP_DEFENSE.push(defense);
}

/** Exact HP multiplier at each step position within one cycle (index 0..17). */
export const CYCLE_STEP_MULTIPLIERS: readonly number[] = STEP_MULT;

/** Exact flat wall defense at each step position within one cycle (resets every cycle). */
export const CYCLE_STEP_DEFENSE: readonly number[] = STEP_DEFENSE;

/** Wall tier at each step position within a cycle. */
export const CYCLE_STEP_TIERS: readonly WallTier[] = [
  'wall', 'wall', 'wall', 'wall', 'wall',
  'ultra', 'ultra', 'ultra', 'ultra', 'ultra',
  'mega', 'mega', 'mega', 'mega', 'mega',
  'power', 'power', 'final',
];

/** Wall level at each step position within a cycle. */
export const CYCLE_STEP_LEVELS: readonly number[] = [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 1];

// Total growth from a rank's starting Wall Lv 1 up to its Final Wall (~3113.9x),
// then crossed by the next cycle boundary (~1.5x) = the full per-cycle growth factor (~4670.87x).
export const CYCLE_TOTAL_GROWTH =
  CYCLE_STEP_MULTIPLIERS[WALL_CYCLE_STEPS - 1] * WALL_CYCLE_BOUNDARY_GROWTH;

// The shared rounded per-cycle factor used by turrets and shop items (matches the ~4671 target).
export const WALL_FINAL_GROWTH_PER_CYCLE = Math.round(CYCLE_TOTAL_GROWTH);

// --- SS-tier probe bonuses (scale with ssLevel: SS1=1, SS2=2, ...) ---
// Wall HP lost to the Zealot each SS level (the wall still grows ×CYCLE_TOTAL_GROWTH per full wall cycle).
export const SS_WALL_HP_PER_LEVEL = 1.15;
// Wall flat defense per SS level.
export const SS_DEFENSE_PER_LEVEL = 1.1;
// Turret attackPower per SS level beyond SS1.
export const SS_TURRET_POWER_PER_LEVEL = 1.25;
// Extra turret count per SS level.
export const SS_TURRET_COUNT_PER_LEVEL = 1;
// Golden Aura: extra wall HP/s regenerated by probes in the SS tier (and above).
export const SS_REGEN_PER_SECOND = 0.02;

// --- SS+ milestone tiers ---
export type TierMechanic = 'goldenAura' | 'novaVolley' | 'overdrive' | 'phaseWalls' | 'realityDrift' | 'finalApex';

export interface TierConfig {
  id: TierId;
  label: string;
  startSsLevel: number;
  timerSeconds: number; // frozen upgrade timer for this tier
  mechanic: TierMechanic;
}

// Every tier lasts SS_LEVELS_PER_TIER displayed levels; timers escalate per tier.
export const TIER_CONFIGS: TierConfig[] = [
  { id: 'SS', label: 'SS', startSsLevel: 1, timerSeconds: 2640, mechanic: 'goldenAura' },
  { id: 'SSS', label: 'SSS', startSsLevel: 51, timerSeconds: 3600, mechanic: 'novaVolley' },
  { id: 'X', label: 'X', startSsLevel: 101, timerSeconds: 4500, mechanic: 'overdrive' },
  { id: 'XD', label: 'XD', startSsLevel: 151, timerSeconds: 5400, mechanic: 'phaseWalls' },
  { id: 'XRD', label: 'XRD', startSsLevel: 201, timerSeconds: 6300, mechanic: 'realityDrift' },
  { id: 'XRFD', label: 'XRFD', startSsLevel: 251, timerSeconds: 7200, mechanic: 'finalApex' },
];

/** Get the tier config for a given tier id. */
export function getTierConfig(tier: TierId): TierConfig {
  return TIER_CONFIGS.find((t) => t.id === tier) || TIER_CONFIGS[0];
}

/** Get the tier config for a current SS level (SS1=1, SS2=2, ...). */
export function getTierConfigBySsLevel(ssLevelNum: number): TierConfig {
  const ordinal = Math.min(getTierOrdinal(getTierStart(ssLevelNum)), TIER_CONFIGS.length - 1);
  return TIER_CONFIGS[ordinal];
}

function getTierStart(ssLevelNum: number): TierId {
  const idx = Math.min(
    Math.floor((Math.max(1, ssLevelNum) - 1) / 50),
    TIER_IDS.length - 1
  );
  return TIER_IDS[idx];
}

export interface TierFlags {
  goldenAura: boolean;
  novaVolley: boolean;
  overdrive: boolean;
  phaseWalls: boolean;
  realityDrift: boolean;
  finalApex: boolean;
}

/** Feature flags per tier: each tier unlocks its own mechanic and keeps all previous ones. */
export function getTierFlags(ssLevelNum: number): TierFlags {
  const ordinal = getTierOrdinal(getTierStart(ssLevelNum));
  return {
    goldenAura: ordinal >= 0,
    novaVolley: ordinal >= 1,
    overdrive: ordinal >= 2,
    phaseWalls: ordinal >= 3,
    realityDrift: ordinal >= 4,
    finalApex: ordinal >= 5,
  };
}

// --- New tier mechanic parameters ---
// SSS Nova Volley: while the probe's ability is active, turret DPS surges for a short window.
export const NOVA_VOLLEY_WINDOW = 4; // seconds the volley lasts
export const NOVA_VOLLEY_DPS_MULT = 3; // x3 turret DPS during the volley

// X Overdrive: turret DPS ramps up while the zealot stays engaged in combat.
export const OVERDRIVE_RAMP_PER_SEC = 0.15; // +15% DPS per engaged second
export const OVERDRIVE_CAP = 20; // +300% overdrive at cap
export const OVERDRIVE_FINAL_CAP = 40; // XRFD ramps even higher

// XD Phase Walls: the wall periodically phases out and becomes invulnerable.
export const PHASE_WALL_INTERVAL = 15; // seconds between phase shifts
export const PHASE_WALL_WINDOW = 4; // invulnerability seconds
export const PHASE_WALL_FINAL_BONUS = 2; // XRFD extends the window

// XRD Reality Drift: when a wall cracks it may resurrect at 30% HP.
export const REALITY_DRIFT_CHANCE = 0.5;
export const REALITY_DRIFT_FINAL_CHANCE = 1.0; // XRFD: guaranteed
export const REALITY_DRIFT_MAX_CHARGES = 2;
export const REALITY_DRIFT_REVIVE_HP = 0.3; // revive at 30% HP