/** Shared scaling constants so walls, shop items and ranks stay in perfect sync. */

// A full rank/cycle advances the upgrade counter by 18 steps (Wall 1-5 -> Ultra 1-5 -> Mega 1-5 -> Power 1-2 -> Final)
export const WALL_CYCLE_STEPS = 18;

// HP multiplier between consecutive wall levels within one cycle (1.5x per level-up)
export const WALL_LEVEL_GROWTH = 1.5;

// HP multiplier on a tier change (Wall -> Ultra -> Mega -> Power -> Final)
export const WALL_TIER_GROWTH = 2.0;

// First Wall of the next rank = 1.5x the Final Wall HP of the previous rank
export const WALL_CYCLE_BOUNDARY_GROWTH = 1.5;

// Total growth from a rank's starting Wall Lv 1 up to its Final Wall:
// 13 level-ups (Wall 1-5, Ultra 1-5, Mega 1-5, Power 1-2) and 4 tier changes.
export const WALL_WITHIN_CYCLE_GROWTH =
  Math.pow(WALL_LEVEL_GROWTH, 13) * Math.pow(WALL_TIER_GROWTH, 4);

// The Final Wall HP - and therefore shop item stats/costs - multiplies by this each completed rank/cycle.
// Items must scale exactly as hard as the Final Wall HP so the Zealot can always smash walls
// with rank-appropriate final-grade items.
export const WALL_FINAL_GROWTH_PER_CYCLE = Math.round(WALL_CYCLE_BOUNDARY_GROWTH * WALL_WITHIN_CYCLE_GROWTH);

// --- SS-tier probe bonuses (scale with ssLevel: SS1=1, SS2=2, ...) ---
// Wall HP lost to the Zealot each SS level (the wall still grows ×4671 per full wall cycle, so this is a bonus on top).
export const SS_WALL_HP_PER_LEVEL = 1.15;
// Wall flat defense per SS level.
export const SS_DEFENSE_PER_LEVEL = 1.1;
// Turret attackPower per SS level beyond SS1.
export const SS_TURRET_POWER_PER_LEVEL = 1.25;
// Extra turret count per SS level.
export const SS_TURRET_COUNT_PER_LEVEL = 1;
// Golden Aura: extra wall HP/s regenerated by SS probes.
export const SS_REGEN_PER_SECOND = 0.02;